# Generated by Django 4.2.20 on 2025-06-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_student_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_enrolled',
        ),
        migrations.AddField(
            model_name='student',
            name='compiler',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='operating_system',
            field=models.BooleanField(default=False),
        ),
    ]
